<?php
/**
 * Implements hook_permission()
 */
function qa_search_permission() {
	return array(
		'view qa search' => array(
			'title' => t('View Q&A Search Pages'),
			'description' => t('View the Question and Answer search pages'),
		),
	);
}

/**
 * Implements hook_menu().
 */
function qa_search_menu() {
	$items = array();

	$items['qasearch'] = array(
		'title' => 'What is it that you are looking for?',
		'description' => 'Home page for looking up using questions and answers',
		'page callback' => 'qa_main_page',
		'access arguments' => array(
			'view qa search',
		),
		'file' => 'qa_search.main_page.inc',
	);

	$items['qasearch/%'] = array(
		'title' => 'Term page',
		'description' => 'Terms with children',
		'page callback' => 'qa_term_page',
		'page arguments' => array(1),
		'access arguments' => array(
			'view qa search',
		),
		'file' => 'qa_search.term_page.inc',
	);

	return $items;
}

/**
 * Implements hook_theme().
 */
function qa_search_theme($existing, $type, $theme, $path) {
	return array(
		'category' => array(
			'variables' => array(
				'term' => NULL,
			),
			'template' => 'category',
			'path' => drupal_get_path('module', 'qa_search') . '/templates',
		),
		'qa_search_main_page' => array(
			'variables' => array(
				'intro_text' => NULL,
				'categories' => NULL,
			),
			'template' => 'main_page',
			'path' => drupal_get_path('module', 'qa_search') . '/templates',
		),
		'qa_search_term_page' => array(
			'variables' => array(
				'edit_link' => NULL,
				'total_url' => NULL,
				'total_nodes' => NULL,
				'question' => NULL,
				'categories' => NULL,
			),
			'template' => 'term_page',
			'path' => drupal_get_path('module', 'qa_search') . '/templates',
			'preprocess functions' => array('qa_search_preprocess_qa_search_term_page'),
		),
		'qa_search_nodes' => array(
			'variables' => array(
				'title' => NULL,
				'nodes' => NULL,
			),
			'template' => 'nodes',
			'path' => drupal_get_path('module', 'qa_search') . '/templates',
		),
	);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function qa_search_preprocess_category(&$variables) {
	$term = $variables['term'];
	$url = _get_term_url($term);
	$parent_id = key(taxonomy_get_parents($term->tid));
	$variables['term_name'] = $term->name;
	$variables['node_count'] = _count_nodes_by_term($term->tid);
	$variables['url'] = $url;
	$variables['no_children'] = empty(taxonomy_get_children($term->tid));
	$variables['short_description'] = $term->field_short_description['und'][0]['value'];

	if (user_access('administer taxonomy')) {
		$variables['edit_term_link'] = l(t('Edit term'), $base_url . '/taxonomy/term/' . $term->tid . '/edit', array('attributes' => array('class' => 'btn btn-default btn-sm', 'style' => 'padding: 0 5px; margin-left: 0.5em;',), 'query' => array('destination' => '/qasearch/' . $parent_id),));
	}
}

/**
* Implements template_preprocess_page().
*/
function qa_search_preprocess_page(&$variables) {
	if (isset($variables['theme_hook_suggestions'][1]) && $variables['theme_hook_suggestions'][1] == 'page__qasearch__%') {
		// $breadcrumb = $variables['page']['content']['system_main']['breadcrumb'];
		// dsm($variables);

		$path = request_path();
		$term_id = intval(explode("/", $path)[1]);
		$breadcrumb = _build_breadcrumb($term_id);

		$variables['breadcrumb'] = theme('item_list', array('items' => $breadcrumb, 'type' => 'ol', 'attributes' => array('class' => 'breadcrumb')));
	}
}

/* Auxiliary functions */
function _get_recursive_url($term) {
	$url_products = '';
	$parents_ids = array();
	$parents = taxonomy_get_parents_all($term->tid);
	
	foreach($parents as $parent) {
		array_unshift($parents_ids, $parent->tid);
	}
	
	foreach ($parents_ids as $parent_id) {
		$url_products .= '&product_category=' . $parent_id;
	}
	
	return '/search/power/#!/?page=1' . $url_products . '&query=';
}

function _get_term_url($term) {
	if (empty(taxonomy_get_children($term->tid))) {
		$url = _get_recursive_url($term);
		$no_children = true;
	} else {
		$url = '/qasearch/' . $term->tid;
		$no_children = false;
	}

	return $url;
}

function _count_nodes_by_term($term) {
	$query = db_select('taxonomy_index', 't');
	$query->condition('tid', $term, '=');
	$query->addExpression('COUNT(*)', 'count_nodes');
	$query->join('node', 'n', 't.nid = n.nid');
	$query->join('field_data_field_status', 's', 't.nid = s.entity_id');
	$query->condition('type', 'product', '=');
	$query->condition('status', 1, '=');
	$query->condition('field_status_value', '3', '!='); // exclude deleted 
	$query->condition('field_status_value', '2', '!='); // exclude discontinued

	$results = $query->execute()->fetchField();

	return $results;
}

function _build_breadcrumb($term) {
	$parents = taxonomy_get_parents_all($term);
	$breadcrumb_array = array();
	$first_term = TRUE;

	foreach($parents as $parent) {
		$term_url = '/qasearch/' . $parent->tid;

		if ($first_term) {
			array_unshift($breadcrumb_array, $parent->name);
			$first_term = FALSE;
		} else {
			array_unshift($breadcrumb_array, l($parent->name, $term_url));
		}
		
	}
	array_unshift($breadcrumb_array, l('Question & Answer Search', '/qasearch'));

	return $breadcrumb_array;
}